{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      namespaceAuth:
        tenantAdminTargetGroup: {{ .Values.Installation.V1.Kubernetes.Auth.TenantAdminTargetGroup }}
        viewAllTargetGroup: {{ .Values.Installation.V1.Kubernetes.Auth.ViewAllTargetGroup }}
{{ end }}
