apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      accessGroups:
        writeAllCustomerGroups:
        {{- if .Values.oidc.customer.write_all_group }}
        - name: {{ .Values.oidc.customer.write_all_group }}
        {{- end }}
        {{- if .Values.oidc.customer.write_all_groups }}
        {{- range .Values.oidc.customer.write_all_groups }}
        - name: {{ . }}
        {{- end }}
        {{- end }}
        writeAllGiantswarmGroups:
        {{- if .Values.oidc.giantswarm.write_all_group }}
        - name: {{ .Values.oidc.giantswarm.write_all_group }}
        {{- end }}
        {{- if .Values.oidc.giantswarm.write_all_groups }}
        {{- range .Values.oidc.giantswarm.write_all_groups }}
        - name: {{ . }}
        {{- end }}
        {{- end }}
        readAllCustomerGroups:
        {{- if .Values.oidc.customer.read_all_group }}
        - name: {{ .Values.oidc.customer.read_all_group }}
        {{- end }}
        {{- if .Values.oidc.customer.read_all_groups }}
        {{- range .Values.oidc.customer.read_all_groups }}
        - name: {{ . }}
        {{- end }}
        {{- end }}        
