apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "resource.pullSecret.name" . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    app: {{ .Values.name }}
data:
  .dockerconfigjson: {{ .Values.registry.pullSecret.dockerConfigJSON | quote }}
