{{ if .Values.Installation.V1.GiantSwarm.OIDC.Enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
{{ end }}
