orbs:
  architect: giantswarm/architect@2.8.0

version: 2.1
jobs:
  build:
    machine: true
    steps:
    - checkout

    - run: |
        wget -q $(curl -sS  https://api.github.com/repos/giantswarm/architect/releases/tags/v1.0.0 | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
        chmod +x ./architect
        ./architect version

    - run: |
        date +"%Y" > /tmp/year
        date +"%m" > /tmp/month
        date +"%d" > /tmp/day
    - restore_cache:
        keys:
        - go-cache-v1-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/month" }}-{{ checksum "/tmp/day" }}
        - go-cache-v1-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/month" }}
        - go-cache-v1-{{ checksum "/tmp/year" }}

    - run: ./architect build

    - store_test_results:
        path: /tmp/results

    - persist_to_workspace:
        root: .
        paths:
        - ./rbac-operator

    - save_cache:
        key: go-cache-v1-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/month" }}-{{ checksum "/tmp/day" }}
        paths:
        - /tmp/go/cache

workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-rbac-operator-to-quay
          image: "quay.io/giantswarm/rbac-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-rbac-operator-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/rbac-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-rbac-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "rbac-operator"
          requires:
            - push-rbac-operator-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      # deploy to all installations (only tags)
      - architect/push-to-app-collection:
          name: push-rbac-operator-to-shared-app-collection
          app_name: "rbac-operator"
          app_collection_repo: "shared-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to aws installations (only tags)
      - architect/push-to-app-collection:
          name: push-rbac-operator-to-aws-app-collection
          app_name: "rbac-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to azure installations (only tags)
      - architect/push-to-app-collection:
          name: push-rbac-operator-to-azure-app-collection
          app_name: "rbac-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to kvm installations (only tags)
      - architect/push-to-app-collection:
          name: push-rbac-operator-to-kvm-app-collection
          app_name: "rbac-operator"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to vmware installations (only tags)
      - architect/push-to-app-collection:
          name: push-rbac-operator-to-vmware-app-collection
          app_name: "rbac-operator"
          app_collection_repo: "vmware-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
