version: 2.1
orbs:
  architect: giantswarm/architect@4.27.0

workflows:
  build:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: rbac-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-rbac-operator-to-quay
          context: architect
          image: "quay.io/giantswarm/rbac-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-rbac-operator-to-aliyun
          context: architect
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/rbac-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-rbac-operator-to-control-plane-app-catalog
          executor: app-build-suite
          context: architect
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "rbac-operator"
          requires:
            - push-rbac-operator-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      # deploy to all installations (only tags)
      - architect/push-to-app-collection:
          name: push-rbac-operator-to-shared-app-collection
          context: architect
          app_name: "rbac-operator"
          app_collection_repo: "shared-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to aws installations (only tags)
      - architect/push-to-app-collection:
          name: push-rbac-operator-to-aws-app-collection
          context: architect
          app_name: "rbac-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to azure installations (only tags)
      - architect/push-to-app-collection:
          name: push-rbac-operator-to-azure-app-collection
          context: architect
          app_name: "rbac-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to openstack installations (only tags)
      - architect/push-to-app-collection:
          name: push-rbac-operator-to-openstack-app-collection
          context: architect
          app_name: "rbac-operator"
          app_collection_repo: "openstack-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to vsphere installations (only tags)
      - architect/push-to-app-collection:
          name: push-rbac-operator-to-vsphere-app-collection
          context: architect
          app_name: "rbac-operator"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-capa-app-collection
          context: architect
          app_name: "rbac-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-cloud-director-app-collection
          app_name: "rbac-operator"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-rbac-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
